=== codehaus/aspectwerkz/aspectwerkz/src/main/aspectwerkz.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--*****************************************************************************************************************************
	AspectWerkz DTD 0.8

This DTD is provided as is. Some elements might have been deprecated since 0.7.4  (see comments)

This DTD might be incomplete - drop a mail on the user / dev mailing list

This DTD might clash with some of existing XML files since it imposes for some elements an order
(see aspect: introductions then pointcuts then advices)

The "unspecified" order of the aspectwerkz childs might change to the one similar of aspects
(transformation scope, introduction-def, advice-def, advices-def, abstract-aspect, aspect, package)

To use this DTD, start your defintion file with
	<!DOCTYPE aspectwerkz PUBLIC
	    "-//AspectWerkz//DTD 0.8//EN"
	    "http://aspectwerkz.codehaus.org/dtd/aspectwerkz_0_8.dtd">
To not use this DTD, start your definition file with
	<?xml version="1.0"?>

******************************************************************************************************************************-->
<!-- aspectwerkz -->
<!--<!ELEMENT aspectwerkz (transformation-scope*, introduction-def*, advice-def*, advices-def*, abstract-aspect*, aspect*, package*)>-->
<!ELEMENT aspectwerkz (transformation-scope*, (introduction-def | advice-def | advices-def | abstract-aspect | aspect | package)*)>
<!ATTLIST aspectwerkz
	id CDATA #REQUIRED
>
<!--*****************************************************************************************************************************
transformation-scope
*********************************************************************************************************************************
Declares one or more global package prefix. Any class not in the scope cannot have aspects on it.
Attributes:
	package: package prefix
Note: package does not support pattern, excepted ending ".*" like "foo.*", which is equivalent to "foo."
During weaving, a class is considered to be in the transformation scope with a classFQN.startsWith( ) test.
******************************************************************************************************************************-->
<!ELEMENT transformation-scope EMPTY>
<!ATTLIST transformation-scope
	package CDATA #REQUIRED
>
<!--*****************************************************************************************************************************
package
*********************************************************************************************************************************
Declares a package prefix which applies to all FQN (introduction, advice) and patterns (pointcuts, class)
contained in the package element. 
Package elements can be nested to ease writing of package and subpackage
(package@name "bar" nested in package@name "foo" means "foo.bar").
Attributes:
	name: package prefix
Note: does not support pattern, excepted ending ".*" like "foo.*" which is equivalent to "foo." and to "foo"
******************************************************************************************************************************-->
<!ELEMENT package (introduction-def*, (advice-def | advices-def)*, abstract-aspect*, aspect*, package*)>
<!ATTLIST package
	name CDATA #REQUIRED
>
<!--*****************************************************************************************************************************
advice-def
*********************************************************************************************************************************
Allow for advice declaration for use in several aspects
Attributes:
	name: unique name of the advice in the system. Referenced in advice-ref@name element
	class: full qualified class name of the advice
	(Deprecated:advice, use class)(Still supported)
	deployment-model: advice life cycle context, defaults to perJVM
	(Deprecated: deploymentModel)
	attribute: ??
To specify other advice param, use nested element advice-def/param
******************************************************************************************************************************-->
<!-- @todo : class REQUIRED, remove advice -->
<!ELEMENT advice-def (param*)>
<!ATTLIST advice-def
	name CDATA #REQUIRED
	class CDATA #IMPLIED
	advice CDATA #IMPLIED
	deployment-model (perJVM | perClass | perInstance | perThread) #IMPLIED
	attribute CDATA #IMPLIED
>
<!ELEMENT param EMPTY>
<!ATTLIST param
	name CDATA #REQUIRED
	value CDATA #REQUIRED
>
<!--*****************************************************************************************************************************
advices-def
*********************************************************************************************************************************
Allow to define an advice stack
******************************************************************************************************************************-->
<!ELEMENT advices-def (advice-ref+)>
<!ATTLIST advices-def
	name CDATA #REQUIRED
>
<!--*****************************************************************************************************************************
introduction-def
*********************************************************************************************************************************
Attributes:
	name: unique name 
	interface: FQN of interface 
	implementation: FQN of class implementing interface to which calls will be delegated 
	deployment-model: advice life cycle context 
	(Deprecated: deploymentModel)
	attribute: ?? 
******************************************************************************************************************************-->
<!ELEMENT introduction-def EMPTY>
<!ATTLIST introduction-def
	name CDATA #REQUIRED
	interface CDATA #REQUIRED
	implementation CDATA #IMPLIED
	deployment-model CDATA #IMPLIED
	attribute CDATA #IMPLIED
>
<!--*****************************************************************************************************************************
abstract-aspect
*********************************************************************************************************************************
Allow for inheritance of aspects
Attributes:
	name: unique name. Referenced in aspect@extends.
?? level of inheritance between abstract-aspects
?? pointcut does not appears here @todo change if pointcut-def gets deprecated
******************************************************************************************************************************-->
<!ELEMENT abstract-aspect ( (introduction-ref | introduction)*, (pointcut-def | controller-def)* , (advices-ref | advice-ref | advice | bind-advice)*)>
<!ATTLIST abstract-aspect
	name CDATA #REQUIRED
>
<!--*****************************************************************************************************************************
aspect
*********************************************************************************************************************************
Attributes:
	name: ??
	extends: abstract-aspect@name
******************************************************************************************************************************-->
<!ELEMENT aspect ((introduction-ref | introduction | bind-introduction)*, (pointcut-def | pointcut | controller-def)*, (advices-ref | advice-ref | advice | bind-advice)*)>
<!ATTLIST aspect
	name CDATA #REQUIRED
	extends CDATA #IMPLIED
>
<!--*****************************************************************************************************************************
pointcut-def and pointcut ???? one will be deprecated soon
*********************************************************************************************************************************
Attributes:
	name
	type
	pattern
Deprecated:	 ??? one will be deprecated soon
******************************************************************************************************************************-->
<!ELEMENT pointcut-def EMPTY>
<!ATTLIST pointcut-def
	name CDATA #REQUIRED
	type (method | getField | setField | throws | callerSide | cflow) #REQUIRED
	pattern CDATA #REQUIRED
>
<!ELEMENT pointcut EMPTY>
<!ATTLIST pointcut
	name CDATA #REQUIRED
	type (method | getField | setField | throws | callerSide | cflow) #REQUIRED
	pattern CDATA #REQUIRED
>
<!--*****************************************************************************************************************************
introduction-ref
*********************************************************************************************************************************
References introduction-def
******************************************************************************************************************************-->
<!ELEMENT introduction-ref EMPTY>
<!ATTLIST introduction-ref
	name CDATA #REQUIRED
>
<!--*****************************************************************************************************************************
advice-ref
*********************************************************************************************************************************
References advice-def
******************************************************************************************************************************-->
<!ELEMENT advice-ref EMPTY>
<!ATTLIST advice-ref
	name CDATA #REQUIRED
>
<!--*****************************************************************************************************************************
advices-ref
*********************************************************************************************************************************
References advices-def
******************************************************************************************************************************-->
<!ELEMENT advices-ref EMPTY>
<!ATTLIST advices-ref
	name CDATA #REQUIRED
>
<!--*****************************************************************************************************************************
introduction
Deprecated - use bind-introduction
*********************************************************************************************************************************
Attributes:
	class: pattern for FQN to apply introduction
Deprecated:	introduce
Note: introduction-ref can be provided both thru a single attribute introduction@introduction-ref and thru one
or more child elements introduction/introduction-ref. The introduction@introduction-ref will ?? be first on stack.
******************************************************************************************************************************-->
<!ELEMENT introduction (introduction-ref*)>
<!ATTLIST introduction
	class CDATA #REQUIRED
	introduction-ref CDATA #IMPLIED
>
<!--*****************************************************************************************************************************
bind-introduction
*********************************************************************************************************************************
Attributes:
	class: pattern for FQN to apply introduction
Deprecated:	introduce
Note: introduction-ref can be provided both thru a single attribute introduction@introduction-ref and thru one
or more child elements introduction/introduction-ref. The introduction@introduction-ref will ?? be first on stack.
******************************************************************************************************************************-->
<!ELEMENT bind-introduction (introduction-ref*)>
<!ATTLIST bind-introduction
	class CDATA #REQUIRED
	introduction-ref CDATA #IMPLIED
>
<!--*****************************************************************************************************************************
advice
Deprecated - use bind-advice
*********************************************************************************************************************************
Attributes:
	pointcut: references pointcut-def@name
	expression: reference an logical combination of pointcut-def@name
	cflow: references pointcut-def@name whose @type is "cflow"
Deprecated:	advise
One and only one of @pointcut and @expression must be present
Note: advice-ref can be provided both thru a single attribute advice@advice-ref and thru one or more child
elements advice/advice-ref. The advice@advice-ref will ?? be first on stack.
******************************************************************************************************************************-->
<!ELEMENT advice (advices-ref | advice-ref)*>
<!ATTLIST advice
	pointcut CDATA #IMPLIED
	expression CDATA #IMPLIED
	cflow CDATA #IMPLIED
	advice-ref CDATA #IMPLIED
>
<!--*****************************************************************************************************************************
bind-advice
*********************************************************************************************************************************
Attributes:
	pointcut: references pointcut-def@name
	expression: reference an logical combination of pointcut-def@name
	cflow: references pointcut-def@name whose @type is "cflow"
One and only one of @pointcut and @expression must be present
Note: advice-ref can be provided both thru a single attribute advice@advice-ref and thru one or more child
elements advice/advice-ref. The advice@advice-ref will ?? be first on stack.
******************************************************************************************************************************-->
<!ELEMENT bind-advice (advices-ref | advice-ref)*>
<!ATTLIST bind-advice
	pointcut CDATA #IMPLIED
	expression CDATA #IMPLIED
	cflow CDATA #IMPLIED
	advice-ref CDATA #IMPLIED
>
<!--*****************************************************************************************************************************
controller-def
Deprecated: controller
*********************************************************************************************************************************
Attributes:
	pointcut: references pointcut-def@name
	expression: reference an logical combination of pointcut-def@name
	class: implementation of the controller
One and only one of @pointcut and @expression must be present
******************************************************************************************************************************-->
<!ELEMENT controller-def EMPTY>
<!ATTLIST controller-def
	pointcut CDATA #IMPLIED
	expression CDATA #IMPLIED
	class CDATA #REQUIRED
>

=== codehaus/aspectwerkz/awbench/src/compiler-extensions/spring/META-INF/aop.xml
<!DOCTYPE aspectwerkz PUBLIC "-//AspectWerkz//DTD//EN" "http://aspectwerkz.codehaus.org/dtd/aspectwerkz.dtd">
<aspectwerkz>
    <system id="awbench">
        <aspect class="awbench.extension.spring.MethodExecutionBeforeAdvice">
            <advice name="before" type="before" bind-to="execution(* awbench.method.Execution.before(..))"/>
        </aspect>
        <aspect class="awbench.extension.spring.MethodExecutionBeforeAdviceSJP">
            <advice name="before" type="before" bind-to="execution(* awbench.method.Execution.beforeSJP(..))"/>
        </aspect>
        <aspect class="awbench.extension.spring.MethodExecutionBeforeAdviceJP">
            <advice name="before" type="before" bind-to="execution(* awbench.method.Execution.beforeJP(..))"/>
        </aspect>
        <aspect class="awbench.extension.spring.MethodExecutionBeforeWithPrimitiveArgsAdvice">
            <advice name="before" type="before" bind-to="execution(* awbench.method.Execution.beforeWithPrimitiveArgs(..))"/>
        </aspect>
        <aspect class="awbench.extension.spring.MethodExecutionAfterAdvice">
            <advice name="afterReturning" type="after returning" bind-to="execution(* awbench.method.Execution.*After(..))"/>
        </aspect>
        <aspect class="awbench.extension.spring.MethodExecutionAfterReturningAdvice">
            <advice name="afterReturning" type="after returning(java.lang.String)" bind-to="execution(* awbench.method.Execution.afterReturningString())"/>
        </aspect>
<!--        <aspect class="awbench.extension.spring.MethodExecutionAfterThrowingAdvice">-->
<!--            <advice name="afterThrowing" type="after throwing(java.lang.RuntimeException)" bind-to="execution(* awbench.method.Execution.afterThrowingRTE())"/>-->
<!--        </aspect>-->
        <aspect name="around1" class="awbench.extension.spring.MethodExecutionGetTargetAndArgsAroundAdvice">
            <advice name="invoke" type="around" bind-to="execution(* awbench.method.Execution.aroundStackedWithArgAndTarget(..))"/>
        </aspect>
        <aspect name="around2" class="awbench.extension.spring.MethodExecutionGetTargetAndArgsAroundAdvice">
            <advice name="invoke" type="around" bind-to="execution(* awbench.method.Execution.aroundStackedWithArgAndTarget(..))"/>
        </aspect>
        <aspect class="awbench.extension.spring.MethodExecutionAroundAdvice">
            <advice name="invoke" type="around" bind-to="execution(* awbench.method.Execution.around_())"/>
        </aspect>
        <aspect class="awbench.extension.spring.MethodExecutionAroundAdviceSJP">
            <advice name="invoke" type="around" bind-to="execution(* awbench.method.Execution.aroundSJP())"/>
        </aspect>
        <aspect class="awbench.extension.spring.MethodExecutionAroundAdviceJP">
            <advice name="invoke" type="around" bind-to="execution(* awbench.method.Execution.aroundJP())"/>
        </aspect>
    </system>
</aspectwerkz>

=== codehaus/aspectwerkz/aspectwerkz4/src/samples/samples-attribdef.xml
<!DOCTYPE aspectwerkz PUBLIC
    "-//AspectWerkz//DTD//EN"
    "http://aspectwerkz.codehaus.org/dtd/aspectwerkz.dtd">
<aspectwerkz>
    <system id="samples">
        <package name="examples">
            <aspect class="caching.Fibonacci$FibonacciCacheAspect" deployment-model="perInstance"/>
            <aspect class="caching.CachingAspect" deployment-model="perInstance" >
                <param name="timeout" value="10"/>
            </aspect>

            <aspect class="introduction.IntroductionAspect" deployment-model="perClass"/>
            <aspect class="cflow.CFlowAspect"/>
            <aspect class="exception.ExceptionHandlingAspect"/>
            <aspect class="logging.ArgAspect"/>
            <aspect class="logging.PreparePointcuts"/>

            <aspect class="annotation.Target$AnnotationMatchAspect"/>

            <!--            <aspect class="logging.XmlDefLoggingAspect">-->
            <!--                <pointcut name="methodsToLog" expression="execution(* examples.logging.Target.toLog*(..))"/>-->
            <!--                <advice name="logMethod" type="around" bind-to="methodsToLog"/>-->
            <!--                <advice name="logBefore" type="before" bind-to="methodsToLog"/>-->
            <!--            </aspect>-->
        </package>
    </system>
</aspectwerkz>

=== codehaus/aspectwerkz/aspectwerkz3/src/samples/samples-attribdef.xml
<!DOCTYPE aspectwerkz PUBLIC
    "-//AspectWerkz//DTD//EN"
    "http://aspectwerkz.codehaus.org/dtd/aspectwerkz.dtd">
<aspectwerkz>
    <system id="samples">
        <prepare package="examples.logging."/>
        <package name="examples">
            <aspect class="caching.Fibonacci$FibonacciCacheAspect" deployment-model="perInstance"/>
            <aspect class="caching.CachingAspect">
                <param name="timeout" value="10"/>
            </aspect>
            <aspect class="logging.LoggingAspect">
                <advice bind-to="execution(* examples.logging.Target.to*(..))" type="before" name="logEntry"/>
                <advice bind-to="execution(* examples.logging.Target.to*(..))" type="after" name="logExit"/>
            </aspect>
            <aspect class="logging.LoggingAspect"/>
            <aspect class="introduction.IntroductionAspect" deployment-model="perClass"/>
            <aspect class="cflow.CFlowAspect"/>
            <aspect class="exception.ExceptionHandlingAspect"/>
        </package>
    </system>
</aspectwerkz>

=== codehaus/aspectwerkz/aspectwerkz/src/samples/aspectwerkz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aspectwerkz PUBLIC "-//AspectWerkz//DTD//EN" "http://aspectwerkz.codehaus.org/dtd/aspectwerkz.dtd">

<aspectwerkz>
  <system id="samples-xmldef">
    <introduction-def name="test1" interface="examples.connectivity.Test1" implementation="examples.connectivity.Test1Impl" deployment-model="perInstance" attribute="test1"/>
    <introduction-def name="test2" interface="examples.connectivity.Test2" implementation="examples.connectivity.Test2Impl" deployment-model="perInstance" attribute="test2"/>
    <introduction-def name="mixin" interface="examples.xmldef.introduction.Mixin" implementation="examples.xmldef.introduction.MixinImpl" deployment-model="perInstance" attribute="mixin"/>
    <advice-def name="org$codehaus$aspectwerkz$advice$CFlowPreAdvice" class="org.codehaus.aspectwerkz.xmldef.advice.CFlowPreAdvice" deployment-model="perThread"/>
    <advice-def name="org$codehaus$aspectwerkz$advice$CFlowPostAdvice" class="org.codehaus.aspectwerkz.xmldef.advice.CFlowPostAdvice" deployment-model="perThread"/>
    <advice-def name="cache" class="examples.xmldef.caching.CachingAdvice" deployment-model="perInstance">
      <param name="timeout" value="10"/>
    </advice-def>
    <advice-def name="log" class="examples.xmldef.logging.LoggingAdvice" deployment-model="perJVM" attribute="log">
      <param name="param" value="value"/>
    </advice-def>
    <advice-def name="asynchronous" class="examples.xmldef.asynchronous.AsynchronousAdvice" deployment-model="perJVM"/>
    <advice-def name="synchronize" class="examples.xmldef.synchronization.SynchronizationAdvice" deployment-model="perJVM"/>
    <advice-def name="cflow" class="examples.xmldef.cflow.LoggingAdvice" deployment-model="perJVM" attribute="cflow"/>
    <advice-def name="invocationCounter" class="examples.xmldef.caching.InvocationCounterAdvice" deployment-model="perInstance" attribute="invocationCounter"/>
    <advice-def name="org$codehaus$aspectwerkz$advice$CFlowPreAdvice" class="org.codehaus.aspectwerkz.xmldef.advice.CFlowPreAdvice" deployment-model="perThread"/>
    <aspect name="org/codehaus/aspectwerkz/system">
      <pointcut-def name="cflowtest" type="cflow" non-reentrant="false" pattern="void examples.xmldef.cflow.Target.step1()"/>
      <pointcut-def name="__aw_method_pointcut_examples_xmldef_cflow_Target0" type="method" pattern="void examples.xmldef.cflow.Target.step2()"/>
      <pointcut-def name="__aw_controller_pointcut_examples_xmldef_logging_Target0" type="method" non-reentrant="false" pattern="void examples.xmldef.logging.Target.toLog1()"/>
      <pointcut-def name="__aw_method_pointcut_examples_xmldef_logging_Target0" type="method" pattern="void examples.xmldef.logging.Target.toLog1()"/>
      <pointcut-def name="__aw_method_pointcut_examples_xmldef_logging_Target1" type="method" pattern="void examples.xmldef.logging.Target.toLog1()"/>
      <pointcut-def name="__aw_method_pointcut_examples_xmldef_logging_Target2" type="method" pattern="void examples.xmldef.logging.Target.toLog2(java.lang.String)"/>
      <pointcut-def name="__aw_method_pointcut_examples_xmldef_logging_Target3" type="method" pattern="java.lang.String examples.xmldef.logging.Target.toLog3()"/>
      <pointcut-def name="__aw_method_pointcut_examples_xmldef_logging_Target4" type="method" pattern="void examples.xmldef.logging.Target.main(java.lang.String[])"/>
      <pointcut-def name="__aw_setfield_pointcut_examples_xmldef_transparentpersistence_Counter0" type="setfield" non-reentrant="false" pattern="int examples.xmldef.transparentpersistence.Counter.m_counter"/>
      <controller-def pointcut="__aw_controller_pointcut_examples_xmldef_logging_Target0" class="examples.xmldef.logging.DummyJoinPointController"/>
      <bind-introduction class="examples.connectivity.Target">
        <introduction-ref name="test1"/>
        <introduction-ref name="test2"/>
      </bind-introduction>
      <bind-introduction class="examples.connectivity.Target">
        <introduction-ref name="test1"/>
        <introduction-ref name="test2"/>
      </bind-introduction>
      <bind-introduction class="examples.xmldef.introduction.Target">
        <introduction-ref name="mixin"/>
      </bind-introduction>
      <bind-advice pointcut="cflowtest">
        <advice-ref name="org$codehaus$aspectwerkz$advice$CFlowPreAdvice"/>
        <advice-ref name="org$codehaus$aspectwerkz$advice$CFlowPostAdvice"/>
      </bind-advice>
      <bind-advice pointcut="__aw_method_pointcut_examples_xmldef_cflow_Target0" cflow="cflowtest">
        <advice-ref name="cflow"/>
      </bind-advice>
      <bind-advice pointcut="__aw_method_pointcut_examples_xmldef_logging_Target0">
        <advice-ref name="log"/>
      </bind-advice>
      <bind-advice pointcut="__aw_method_pointcut_examples_xmldef_logging_Target1">
        <advice-ref name="log"/>
      </bind-advice>
      <bind-advice pointcut="__aw_method_pointcut_examples_xmldef_logging_Target2">
        <advice-ref name="log"/>
      </bind-advice>
      <bind-advice pointcut="__aw_method_pointcut_examples_xmldef_logging_Target3">
        <advice-ref name="log"/>
      </bind-advice>
      <bind-advice pointcut="__aw_method_pointcut_examples_xmldef_logging_Target4">
        <advice-ref name="log"/>
      </bind-advice>
    </aspect>
    <aspect name="Synchronization">
      <pointcut-def name="synchronized_calls" type="method" non-reentrant="true" pattern="* examples.xmldef.synchronization.Target.toSynchronize()"/>
      <bind-advice pointcut="synchronized_calls">
        <advice-ref name="synchronize"/>
      </bind-advice>
    </aspect>
    <aspect name="Caching">
      <pointcut-def name="callee" type="method" non-reentrant="false" pattern="int examples.xmldef.caching.Pi.getPiDecimal(int)"/>
      <pointcut-def name="caller" type="callerSide" non-reentrant="false" pattern="examples.xmldef.caching.*-&gt;int examples.xmldef.caching.Pi.getPiDecimal(int)"/>
      <bind-advice pointcut="callee">
        <advice-ref name="cache"/>
      </bind-advice>
      <bind-advice pointcut="caller">
        <advice-ref name="invocationCounter"/>
      </bind-advice>
    </aspect>
    <aspect name="Asynchronous">
      <pointcut-def name="asynchronous_calls" type="method" non-reentrant="false" pattern="* examples.xmldef.asynchronous.Target.toRunAsynchronously()"/>
      <bind-advice pointcut="asynchronous_calls">
        <advice-ref name="asynchronous"/>
      </bind-advice>
    </aspect>
  </system>
</aspectwerkz>
